name: Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.cabal/store
        key: ${{ matrix.ghc }}-cabal-${{ hashFiles('**/fallible.cabal') }}
        restore-keys: |
          ${{ matrix.ghc }}-cabal-

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies
    - name: Build Generator
      run: cabal install --installdir="."
    - name: Generate HTMLs
      run: ./intro-haskell-exe ./assets
    - uses: actions/upload-pages-artifact@v1
      with:
        path: out

  deploy:
    needs: generate
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
