name: Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      id: cache-stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: "\
          ${{ runner.os }}-stack\
          -${{ hashFiles('**/stack.yaml.lock') }}\
          -${{ hashFiles('**/package.yaml') }}\
        "
        restore-keys: |
          ${{ runner.os }}-stack-

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        enable-stack: true
        stack-version: 'latest'

    - name: Install dependencies
      run: stack --system-ghc build --only-dependencies
    - name: Build Generator
      run: stack --system-ghc install --local-bin-path .
    - name: Generate HTMLs
      run: ./intro-haskell-exe ./assets
    - uses: actions/upload-pages-artifact@v1
      with:
        path: out

  deploy:
    needs: generate
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
